# firmware_gen.py
# Generates config.py and sensors.py content for transmitter nodes,
# and handles flashing (copying files) to a mounted CircuitPython board.

import os
import shutil

from sensor_defs import CHANNEL_DEFS, pct_to_adc, build_read_fn_body


# --- Path to hardware/shared/ relative to this file ---

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_THIS_DIR)
_SHARED_DIR = os.path.join(_REPO_ROOT, "hardware", "shared")
_HARDWARE_DIR = os.path.join(_REPO_ROOT, "hardware")


# ---------------------------------------------------------------------------
# config.py generation
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# =============================================================
# Transmitter Node Configuration
# Flash this file to each node and edit values to match the
# physical setup. No other files should need to change between nodes.
# =============================================================

# --- Network Identity ---
LAB_ID  = {lab_id:#04x}   # Physical lab this node belongs to (1-255, 0 reserved)
NODE_ID = {node_id:#04x}   # Unique ID matching the physical label on this enclosure (1-255)

# --- Radio ---
RADIO_FREQ_MHZ = 915.0  # Hz. Must match receiver exactly.
TX_POWER       = 5      # dBm (5-23). Keep low if USB disconnects during TX.

# --- Timing ---
HEARTBEAT_INTERVAL = 30   # Seconds. Heartbeat sent if no event in this window.
POLL_INTERVAL      = 1    # Seconds between sensor reads.

# --- Sensor Definitions ---
{sensors_block}
"""


def generate_config(lab_id, node_id, sensors):
    """Generate config.py content.

    sensors: list of dicts, each with "channel" key (and optional extras).
    Returns a string.
    """
    lines = ["SENSORS = ["]
    for s in sensors:
        lines.append('    {{"channel": "{}"}},'.format(s["channel"]))
    lines.append("]")
    sensors_block = "\n".join(lines)
    return _CONFIG_TEMPLATE.format(
        lab_id=lab_id,
        node_id=node_id,
        sensors_block=sensors_block,
    )


# ---------------------------------------------------------------------------
# sensors.py generation
# ---------------------------------------------------------------------------

def generate_sensors(sensors):
    """Generate sensors.py content.

    sensors: list of dicts, each with:
        "channel": str  (key into CHANNEL_DEFS)
        "params":  dict (field name -> value from the UI)
    Returns a string.
    """
    # Collect unique imports, pin setups, constants, read functions
    imports_set = set()
    pin_setups = []
    constants_lines = []
    read_fns = []
    readers_entries = []
    trigger_entries = []

    for sensor in sensors:
        channel = sensor["channel"]
        params = sensor.get("params", {})
        defn = CHANNEL_DEFS[channel]

        # Imports
        for imp in defn["imports"]:
            imports_set.add(imp)

        # Pin setup — params already contains "pin", pass everything together
        fmt_vars = dict(params)
        if "pin" not in fmt_vars:
            fmt_vars["pin"] = defn["fields"][0].get("default", "A0")
        setup = defn["pin_setup"].format(**fmt_vars)
        pin_setups.append(setup)

        # Constants
        if defn["constants"]:
            if "threshold_pct" in params:
                raw = pct_to_adc(params["threshold_pct"])
                const_line = defn["constants"].format(threshold_raw=raw, **params)
            else:
                const_line = defn["constants"].format(**params)
            constants_lines.append(const_line)

        # Read function
        fn_name = defn["read_fn_name"]
        unit_long = "Fahrenheit" if params.get("unit") == "F" else "Celsius"
        doc = defn["read_fn_doc"].format(unit_long=unit_long, **params)
        body = build_read_fn_body(channel, params)
        read_fns.append(
            'def {name}():\n'
            '    """{doc}"""\n'
            '{body}'.format(name=fn_name, doc=doc, body=body)
        )

        # READERS entry
        ret_type = defn["read_fn_return"]
        readers_entries.append(
            '    "{ch}": {fn},   # () -> {ret}'.format(
                ch=channel, fn=fn_name, ret=ret_type
            )
        )

        # TRIGGER_TYPE entry
        if defn["trigger_type"]:
            trigger_entries.append(
                '    "{ch}": "{tt}",'.format(ch=channel, tt=defn["trigger_type"])
            )

    # --- Sort imports: stdlib first, then third-party/board ---
    sorted_imports = sorted(imports_set)

    # --- Build header comment ---
    channel_names = [s["channel"] for s in sensors]
    header_comment = (
        "# sensors.py\n"
        "# Auto-generated by Sensor Flasher.\n"
        "# Channels: {}\n".format(", ".join(channel_names))
    )

    # --- Assemble file ---
    sections = []

    # Header
    sections.append(header_comment)

    # Imports
    sections.append("\n".join(sorted_imports))

    # Pin setup
    sections.append(
        "# ---------------------------------------------------------------------------\n"
        "# Pin setup\n"
        "# ---------------------------------------------------------------------------\n"
        "\n" + "\n\n".join(pin_setups)
    )

    # Constants (if any)
    if constants_lines:
        sections.append(
            "# ---------------------------------------------------------------------------\n"
            "# Thresholds\n"
            "# ---------------------------------------------------------------------------\n"
            "\n" + "\n".join(constants_lines)
        )

    # Read functions
    sections.append(
        "# ---------------------------------------------------------------------------\n"
        "# Public interface\n"
        "# ---------------------------------------------------------------------------\n"
        "\n" + "\n\n\n".join(read_fns)
    )

    # READERS dict
    readers_block = "READERS = {\n" + "\n".join(readers_entries) + "\n}"

    # TRIGGER_TYPE dict
    trigger_block = "TRIGGER_TYPE = {\n" + "\n".join(trigger_entries) + "\n}"

    sections.append(
        "# ---------------------------------------------------------------------------\n"
        "# Generic interface for shared/code.py\n"
        "# ---------------------------------------------------------------------------\n"
        "\n" + readers_block + "\n\n" + trigger_block
    )

    return "\n\n".join(sections) + "\n"


# ---------------------------------------------------------------------------
# Flash to board
# ---------------------------------------------------------------------------

def flash_to_board(mount_path, config_content, sensors_content):
    """Write generated firmware files to a mounted CircuitPython board.

    Copies:
        config.py   (generated)
        sensors.py  (generated)
        code.py     (from hardware/shared/)
        packet.py   (from hardware/shared/)

    Returns a (success: bool, message: str) tuple.
    """
    if not os.path.isdir(mount_path):
        return False, "Mount path '{}' does not exist or is not accessible.".format(mount_path)

    shared_code = os.path.join(_SHARED_DIR, "code.py")
    shared_packet = os.path.join(_SHARED_DIR, "packet.py")
    for path in (shared_code, shared_packet):
        if not os.path.isfile(path):
            return False, "Required shared file not found: {}".format(path)

    try:
        # Write generated files
        config_path = os.path.join(mount_path, "config.py")
        with open(config_path, "w", newline="\n") as f:
            f.write(config_content)

        sensors_path = os.path.join(mount_path, "sensors.py")
        with open(sensors_path, "w", newline="\n") as f:
            f.write(sensors_content)

        # Copy shared files
        shutil.copy2(shared_code, os.path.join(mount_path, "code.py"))
        shutil.copy2(shared_packet, os.path.join(mount_path, "packet.py"))

        return True, "Flashed 4 files to {}".format(mount_path)
    except OSError as e:
        return False, "Flash failed: {}".format(e)


# ---------------------------------------------------------------------------
# Save to repo
# ---------------------------------------------------------------------------

def save_to_repo(transmitter_name, config_content, sensors_content):
    """Save generated firmware files to hardware/<transmitter_name>/.

    Creates the directory if it does not exist.
    Returns a (success: bool, message: str) tuple.
    """
    tx_dir = os.path.join(_HARDWARE_DIR, transmitter_name)
    try:
        os.makedirs(tx_dir, exist_ok=True)
        config_path = os.path.join(tx_dir, "config.py")
        with open(config_path, "w", newline="\n") as f:
            f.write(config_content)

        sensors_path = os.path.join(tx_dir, "sensors.py")
        with open(sensors_path, "w", newline="\n") as f:
            f.write(sensors_content)

        return True, "Saved to {}".format(tx_dir)
    except OSError as e:
        return False, "Save failed: {}".format(e)


# ---------------------------------------------------------------------------
# Discover existing transmitter types
# ---------------------------------------------------------------------------

def list_transmitter_types():
    """Return a list of existing transmitter directory names under hardware/.

    Looks for directories matching *-transmitter/.
    """
    types = []
    if not os.path.isdir(_HARDWARE_DIR):
        return types
    for name in sorted(os.listdir(_HARDWARE_DIR)):
        if name.endswith("-transmitter") and os.path.isdir(os.path.join(_HARDWARE_DIR, name)):
            types.append(name)
    return types


def load_transmitter_config(transmitter_name):
    """Parse an existing transmitter's config.py and return extracted values.

    Returns a dict with lab_id, node_id, and sensors list, or None on failure.
    """
    config_path = os.path.join(_HARDWARE_DIR, transmitter_name, "config.py")
    if not os.path.isfile(config_path):
        return None

    namespace = {}
    try:
        with open(config_path, "r") as f:
            exec(compile(f.read(), config_path, "exec"), namespace)
    except Exception:
        return None

    return {
        "lab_id": namespace.get("LAB_ID", 1),
        "node_id": namespace.get("NODE_ID", 1),
        "sensors": namespace.get("SENSORS", []),
    }
