def compose_sensors_py(sensors):
    """Build a complete sensors.py from a list of configured sensors.

    Each entry: {"template": parsed_template, "param_values": {key: value}}
    """
    all_imports = []
    seen_imports = set()
    setup_lines = []
    seen_setup = set()
    read_blocks = []
    channels = []
    trigger_types = {}

    for sensor in sensors:
        tmpl = sensor["template"]
        params = sensor["param_values"]
        channel = tmpl["channel"]
        channels.append(channel)

        # Substitute {param} placeholders in each section
        imports_text = tmpl["sections"]["imports"]
        setup_text = tmpl["sections"]["setup"]
        read_text = tmpl["sections"]["read"]

        for key, val in params.items():
            placeholder = "{" + key + "}"
            imports_text = imports_text.replace(placeholder, str(val))
            setup_text = setup_text.replace(placeholder, str(val))
            read_text = read_text.replace(placeholder, str(val))

        # Collect imports (deduplicate, preserve order)
        for line in imports_text.splitlines():
            stripped = line.strip()
            if stripped and stripped not in seen_imports:
                all_imports.append(stripped)
                seen_imports.add(stripped)

        # Collect setup lines (deduplicate identical lines for shared resources)
        for line in setup_text.splitlines():
            stripped = line.strip()
            if stripped and stripped not in seen_setup:
                setup_lines.append(line)
                seen_setup.add(stripped)

        read_blocks.append(read_text)

        if tmpl["trigger"] == "edge":
            trigger_types[channel] = "edge"

    # Assemble the file
    parts = []
    parts.append("# sensors.py")
    parts.append("# Generated by Flash Device tab")
    parts.append("#")
    for ch in channels:
        parts.append("#   read_{}()".format(ch))

    parts.append("")
    parts.append("import board")
    for imp in all_imports:
        parts.append(imp)

    parts.append("")
    parts.append("# " + "-" * 75)
    parts.append("# Pin setup")
    parts.append("# " + "-" * 75)
    parts.append("")
    parts.extend(setup_lines)

    parts.append("")
    parts.append("")
    parts.append("# " + "-" * 75)
    parts.append("# Public interface")
    parts.append("# " + "-" * 75)
    parts.append("")
    parts.append("\n\n".join(read_blocks))

    parts.append("")
    parts.append("")
    parts.append("# " + "-" * 75)
    parts.append("# Generic interface for shared/code.py")
    parts.append("# " + "-" * 75)
    parts.append("")
    parts.append("READERS = {")
    for ch in channels:
        parts.append("    \"{}\": read_{},".format(ch, ch))
    parts.append("}")
    parts.append("")
    parts.append("TRIGGER_TYPE = {")
    for ch in channels:
        if ch in trigger_types:
            parts.append("    \"{}\": \"{}\",".format(ch, trigger_types[ch]))
    parts.append("}")
    parts.append("")

    return "\n".join(parts)


def compose_config_py(lab_id, node_id, sensors):
    """Build a config.py from node identity and sensor list."""
    channels = [s["template"]["channel"] for s in sensors]
    sensor_entries = "\n".join(
        "    {{\"channel\": \"{}\"}},".format(ch) for ch in channels
    )

    return (
        "# =============================================================\n"
        "# Transmitter Node Configuration\n"
        "# Generated by Flash Device tab\n"
        "# =============================================================\n"
        "\n"
        "# --- Network Identity ---\n"
        "LAB_ID  = {lab:#04x}   # Physical lab this node belongs to (1-255, 0 reserved)\n"
        "NODE_ID = {node:#04x}   # Unique ID for this transmitter board (1-255)\n"
        "\n"
        "# --- Radio ---\n"
        "RADIO_FREQ_MHZ = 915.0\n"
        "TX_POWER       = 5\n"
        "RECEIVER_NODE  = 0x01\n"
        "ACK_RETRIES    = 3\n"
        "ACK_WAIT       = 0.5\n"
        "CSMA_DELAY_MAX = 0.1\n"
        "\n"
        "# --- Timing ---\n"
        "HEARTBEAT_INTERVAL = 30\n"
        "POLL_INTERVAL      = 1\n"
        "\n"
        "# --- Sensor Definitions ---\n"
        "SENSORS = [\n"
        "{entries}\n"
        "]\n"
    ).format(lab=lab_id, node=node_id, entries=sensor_entries)
